// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using strange.extensions.context.api;
using strange.extensions.context.impl;

public class ContextMapperFactory
{
	public static Action<ICrossContextCapable> createFirstRun( Action<ICrossContextCapable> action )
	{
		Action<ICrossContextCapable> wrapper = delegate( ICrossContextCapable context )
		{
			if( Context.firstContext == context )
			{
				action( context );
			}
		};
		return wrapper;
	}
}

